GET http://localhost:4997/projetos

###
GET http://localhost:4997/projetos/1

###
DELETE http://localhost:4997/projetos/29

###
POST http://localhost:4997/projetos
Content-Type: application/json

{ 
  "nome": "Projeto Botucatu",
  "descricao": "Projeto destinado a prefeitura de Botucatu"
}
