GET http://localhost:4997/projetos

###
GET http://localhost:4997/projetos/3

###
GET http://localhost:4997/projetos/comescolas/1

###
GET http://localhost:4997/projetos/itens

###
DELETE http://localhost:4997/projetos/29


###
POST http://localhost:4997/projetos
Content-Type: application/json

{   
  "id": 1,
  "url": "/joinville.png"
}
