GET http://localhost:4997/escolas

###
GET http://localhost:4997/escolas/1

###
GET http://localhost:4997/escolas/full/51
###
DELETE http://localhost:4997/escolas/27

###
POST http://localhost:4997/escolas
Content-Type: application/json

{ 
  "nome": "Escola Papa Pio XVII",
  "projetoId": 3
}
