GET http://localhost:4997/escolas

###
GET http://localhost:4997/escolas/305

###
GET http://localhost:4997/escolas/full/309
###
DELETE http://localhost:4997/escolas/300

###
POST http://localhost:4997/escolas
Content-Type: application/json

{ 
  "nome": "Escola Papa Pio XVII",
  "projetoId": 3
}
